---
# playbooks/site.yml
# Minimal placeholder playbook

- name: Test Ansible syntax with Nginx
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Dummy task to pass syntax check
      debug:
        msg: "Ansible syntax is correct!"
  roles:
    - common
    - docker
    - nginx
