- name: Include upstream nginx role
  block:
    # checkov:skip=CKV2_ANSIBLE_3 "Upstream Galaxy role handles errors internally"
    - import_role:
        name: geerlingguy.nginx
  rescue:
    - name: Log nginx role failure
      debug:
        msg: "geerlingguy.nginx role failed!"
  always:
    - name: Finished nginx import block
      debug:
        msg: "geerlingguy.nginx role import completed"
